# Find the best linker available (skip on window)
function(find_linker)
    if(MSVC)
        return()
    endif()
    message(STATUS "Looking for mold")
    find_program(MOLD_FOUND mold)
    if(MOLD_FOUND)
        message(STATUS "Looking for mold - found")
    else()
        message(STATUS "Looking for mold - not found")
    endif()
    message(STATUS "Looking for lld")
    find_program(LLD_FOUND lld)
    if(LLD_FOUND)
        message(STATUS "Looking for lld - found")
    else()
        message(STATUS "Looking for lld - not found")
    endif()

    if(MOLD_FOUND)
        message(STATUS "Linker used - mold")
        set(CMAKE_C_LINKER_FLAGS "-fuse-ld=lld")
        set(CMAKE_CXX_LINKER_FLAGS "-fuse-ld=lld")
        set(CMAKE_EXE_LINKER_FLAGS "-fuse-ld=lld")
    elseif(LLD_FOUND)
        message(STATUS "Linker used - lld")
        set(CMAKE_C_LINKER_FLAGS "-fuse-ld=lld")
        set(CMAKE_CXX_LINKER_FLAGS "-fuse-ld=lld")
        set(CMAKE_EXE_LINKER_FLAGS "-fuse-ld=lld")
    endif()
endfunction(find_linker)
