# Find the best linker available (skip on window)
function(find_linker)
    if (MSVC)
        return()
    endif()
    message(STATUS "Looking for lld")
    find_program(LLD_FOUND lld)
    if (LLD_FOUND)
        message(STATUS "Looking for lld - found")
        set(CMAKE_C_LINKER_FLAGS "-fuse-ld=lld")
        set(CMAKE_CXX_LINKER_FLAGS "-fuse-ld=lld")
        set(CMAKE_EXE_LINKER_FLAGS "-fuse-ld=lld")
    else()
        message(STATUS "Looking for lld - not found")
    endif()
endfunction(find_linker)

