intf_libs = # Interface dependencies.
impl_libs = # Implementation dependencies.

lib{ecs}: {hxx mxx cxx}{** -version} hxx{version} $impl_libs $intf_libs

# Include the generated version header into the distribution (so that we don't
# pick up an installed one) and don't remove it when cleaning in src (so that
# clean results in a state identical to distributed).
#
hxx{version}: in{version} $src_root/manifest
{
  dist  = true
  clean = ($src_root != $out_root)
}

hxx{export}@./: cxx.importable = false

# Build options.
#
cxx.poptions =+ "-I$out_root" "-I$src_root"

{hbmia obja}{*}: cxx.poptions += -DLIBECS_STATIC_BUILD
{hbmis objs}{*}: cxx.poptions += -DLIBECS_SHARED_BUILD

# Export options.
#
lib{ecs}:
{
  cxx.export.poptions = "-I$out_root" "-I$src_root"
  cxx.export.libs = $intf_libs
}

liba{ecs}: cxx.export.poptions += -DLIBECS_STATIC
libs{ecs}: cxx.export.poptions += -DLIBECS_SHARED

# For pre-releases use the complete version to make sure they cannot be used
# in place of another pre-release or the final version. See the version module
# for details on the version.* variable values.
#
if $version.pre_release
  lib{ecs}: bin.lib.version = @"-$version.project_id"
else
  lib{ecs}: bin.lib.version = @"-$version.major.$version.minor"

# Install into the libecs/ subdirectory of, say, /usr/include/
# recreating subdirectories.
#
{hxx mxx}{*}:
{
  install         = include/libecs/
  install.subdirs = true
}
